version: 2
updates:
  - package-ecosystem: docker
    directory: /base
    schedule:
      interval: monthly
  - package-ecosystem: docker
    directory: /nodejs
    schedule:
      interval: monthly
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
