name: build and push devcontainer-nodejs

on:
  push:
    paths:
      - "nodejs/**"
      - ".github/workflows/build-push.yaml"
      - ".github/workflows/build-push-nodejs.yaml"
  pull_request:
    paths:
      - "nodejs/**"
      - ".github/workflows/build-push.yaml"
      - ".github/workflows/build-push-nodejs.yaml"
  workflow_dispatch:

jobs:
  build-and-push:
    name: Build and Push devcontainer-nodejs
    permissions:
      contents: read
      packages: write
      # This is used to complete the identity challenge
      # with sigstore/fulcio when running outside of PRs.
      id-token: write
    uses: ./.github/workflows/build-push.yaml
    with:
      image-name: devcontainer-nodejs
      context-directory: nodejs
