name: build and push devcontainer-base

on:
  push:
    paths:
      - "base/**"
      - ".github/workflows/build-push.yaml"
      - ".github/workflows/build-push-base.yaml"
  pull_request:
    paths:
      - "base/**"
      - ".github/workflows/build-push.yaml"
      - ".github/workflows/build-push-base.yaml"
  workflow_dispatch:

jobs:
  build-and-push:
    name: Build and Push devcontainer-base
    permissions:
      actions: read
      contents: read
      packages: write
      # This is used to complete the identity challenge
      # with sigstore/fulcio when running outside of PRs.
      id-token: write
    uses: ./.github/workflows/build-push.yaml
    with:
      image-name: devcontainer-base
      context-directory: base
